### ISSUE TITLE
The Dragun Skull doesn't syngerise with the Dragun Heart

### ISSUE THREAD

**Issue by Antiiilluminati** [UnstableStrafe/ChildrenOfKaliber#5]
No idea what this combo would do, but it would be really cool to collect all the pieces of the dragun and get like a pet or something

**Comment by UnstableStrafe** [comment]
They do have a synergy together, though it also requires the Dragun Wing and Dragun Claw. Having one of the four items makes finding the others much more likely too

**Comment by Antiiilluminati** [comment]
Ah ok, that makes alot more sense.

Can't wait to find all of the items now!
